---
swagger: "2.0"
info:
  version: "2022-05-26T01:07:59Z"
  title: "pats1"
host: "cvm5zxkwhh.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/hoge"
schemes:
- "https"
paths:
  /:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "https://classmethod.jp/"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "http_proxy"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"